import { useEffect, useState, useRef, type FormEvent } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowUpRight, ArrowDown, ArrowUp, Sun, Moon, Menu, X, Code2, Braces, GraduationCap, BriefcaseBusiness, Award, ChevronDown, BrainCircuit, Layers3, ShieldCheck, Database, FileText, Users, Calendar, CreditCard, Workflow, Building2, Github, Linkedin, Mail, MapPin, Send, ArrowRight, UserRound, Atom, Terminal, Globe, LockKeyhole } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { portfolio as p } from '@/data/portfolio';
import stack from '@/assets/engineering-stack.jpg';
import lightStack from '@/assets/engineering-stack-light.jpg';
import { Count, Reveal, Tags, SectionHeading, skillIcons } from './elements';

const featureIcons=[Database,Users,FileText,ShieldCheck,BrainCircuit,Building2,Calendar,CreditCard,Workflow,Layers3];
const appIcons=[UserRound,Building2,Users,Terminal,Calendar,Globe];
export function PortfolioPage(){
  const [light,setLight]=useState(true);const [menu,setMenu]=useState(false);const [active,setActive]=useState('');const [role,setRole]=useState(0);const [typed,setTyped]=useState('');const [filter,setFilter]=useState('All');const [expanded,setExpanded]=useState<number[]>([]);const [feedback,setFeedback]=useState('');const reduced=useReducedMotion();const cursor=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(reduced||!window.matchMedia('(pointer: fine)').matches)return;const move=(event:PointerEvent)=>{if(cursor.current){cursor.current.style.transform=`translate(${event.clientX}px,${event.clientY}px)`;cursor.current.style.opacity='.35';}};window.addEventListener('pointermove',move);return()=>window.removeEventListener('pointermove',move);},[reduced]);
  useEffect(()=>{setLight(localStorage.getItem('portfolio-theme-v2')!=='dark');},[]);
  useEffect(()=>{document.documentElement.classList.toggle('light',light);document.documentElement.classList.toggle('dark',!light);},[light]);
  useEffect(()=>{if(reduced){setTyped(p.roles[0] ?? '');return;}const word=p.roles[role] ?? '';let length=0;const typing=setInterval(()=>{length++;setTyped(word.slice(0,length));if(length>=word.length)clearInterval(typing);},65);const next=setTimeout(()=>{setRole(v=>(v+1)%p.roles.length);},2800);return()=>{clearInterval(typing);clearTimeout(next);};},[role,reduced]);
  useEffect(()=>{const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id);});},{rootMargin:'-15% 0px -65% 0px'});p.navigation.forEach(n=>{const element=document.getElementById(n.toLowerCase());if(element)observer.observe(element);});return()=>observer.disconnect();},[]);
  function toggleTheme(){setLight(v=>{localStorage.setItem('portfolio-theme-v2',v?'dark':'light');return !v;});}
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!p.contact.email){setFeedback(p.labels.contactUnavailable);return;}const data=new FormData(e.currentTarget);window.location.href=`mailto:${p.contact.email}?subject=${encodeURIComponent('Portfolio enquiry from '+String(data.get('name')))}&body=${encodeURIComponent(String(data.get('message'))+'\n\n'+String(data.get('email')))}`;}
  return <div className="portfolio"><div ref={cursor} className="cursor-trace" aria-hidden="true"/>
    <header className="site-header"><div className="container header-inner"><a href="#" className="brand" aria-label="Karthick A home"><span className="brand-mark"><Braces size={21}/></span>{p.name}<span className="text-primary">.</span></a><nav aria-label="Main navigation" className="desktop-nav">{p.navigation.map(n=><a key={n} href={`#${n.toLowerCase()}`} className={active===n.toLowerCase()?'active':''}>{n}</a>)}</nav><div className="flex gap-2"><Button size="icon" variant="ghost" onClick={toggleTheme} aria-label={light?'Switch to dark theme':'Switch to light theme'} title={light?'Dark theme':'Light theme'}>{light?<Moon size={18}/>:<Sun size={18}/>}</Button><Button className="mobile-menu-button" size="icon" variant="ghost" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></div></div>{menu&&<nav className="mobile-nav" aria-label="Mobile navigation">{p.navigation.map(n=><a key={n} href={`#${n.toLowerCase()}`} onClick={()=>setMenu(false)}>{n}</a>)}</nav>}</header>
    <main>
      <section className="hero"><img className="hero-art" src={light?lightStack:stack} alt="Layered glass processors connected by illuminated cyan circuits" width={1536} height={1024}/><div className="hero-grid"/><div className="container hero-content"><div className="eyebrow hero-eyebrow"><span className="hero-line"/> FULL STACK · DEVOPS · ARTIFICIAL INTELLIGENCE</div><h1>{p.heroName.split(' ')[0]}<br/><span>{p.heroName.split(' ')[1]}<span className="name-period">.</span></span></h1><div className="typing-line"><span className="text-secondary">&gt;</span><span aria-hidden="true">{typed}<span className="typing-cursor">_</span></span><span className="sr-only">{p.roles.join(' | ')}</span></div><p className="hero-description">{p.intro}</p><div className="hero-actions"><Button asChild size="lg"><a href="#projects">{p.labels.viewProjects}<ArrowUpRight/></a></Button><Button asChild size="lg" variant="outline"><a href="#about">{p.labels.aboutMe}<ArrowRight/></a></Button></div></div><div className="container hero-bottom"><a href="#about" className="scroll-indicator" aria-label="Scroll to About"><ArrowDown size={17}/><span>01 — 06</span></a><div className="hero-stack-label"><Code2 size={15}/><span>Python</span><span>React</span><span>FastAPI</span><span>AI Agents</span></div></div></section>
      <section id="about" className="section"><div className="container"><SectionHeading number="01" label="ABOUT ME" title={p.aboutHeading}/><div className="about-grid"><Reveal className="photo-placeholder"><div className="photo-frame"><UserRound strokeWidth={.7} size={110}/><span>{p.labels.photo}</span></div><div className="photo-caption"><Braces size={19}/><span>{p.name}</span><span className="text-secondary font-mono">&lt;/&gt;</span></div></Reveal><Reveal><h3 className="journey-title">{p.journeyHeading}</h3><div className="journey-list">{p.journey.map((j,i)=><div key={j} className="journey-item"><span className="journey-icon">{i<3?<BriefcaseBusiness size={17}/>:<GraduationCap size={18}/>}</span><p>{j}</p></div>)}</div></Reveal></div><Reveal className="stats-row">{p.stats.map(s=><div key={s.label}><strong><Count value={s.value} suffix={s.suffix}/></strong><span>{s.label}</span></div>)}</Reveal></div></section>
      <section id="skills" className="section section-tinted"><div className="container"><SectionHeading number="02" label="THE TOOLKIT" title={p.skillsHeading}/><div className="skills-grid">{p.skills.map((s,i)=>{const Icon=skillIcons[i] ?? Code2;return <Reveal key={s.name} className="skill"><div className="skill-label"><span className="flex items-center gap-3"><Icon size={20}/>{s.name}</span><span className="font-mono text-muted-foreground">{s.value}<small>%</small></span></div><div className="skill-track"><motion.div initial={{width:reduced?`${s.value}%`:0}} whileInView={{width:`${s.value}%`}} viewport={{once:true}} transition={{duration:reduced?0:1}} className="skill-fill"/></div></Reveal>;})}</div></div></section>
      <section id="experience" className="section"><div className="container"><SectionHeading number="03" label="EXPERIENCE" title={p.experienceHeading}/><div className="timeline">{p.experience.map((e,i)=><Reveal key={e.company} className={`timeline-entry ${i%2?'timeline-right':''}`}><div className="timeline-marker"><BriefcaseBusiness size={17}/></div><div className="experience-card"><div className="experience-top"><span className="font-mono text-secondary">{e.date}</span><span className="duration">{e.duration}</span></div><h3>{e.role}</h3><h4>{e.company}</h4><p className="experience-description">{e.description}</p><h5>{p.labels.achievements}</h5><ul>{e.achievements.map(a=><li key={a}>{a}</li>)}</ul><Tags items={e.tech}/></div></Reveal>)}</div></div></section>
      <section id="certifications" className="section section-tinted"><div className="container"><SectionHeading number="04" label="CERTIFICATIONS" title={p.certificationsHeading}/><div className="cert-grid">{p.certifications.map((c,i)=><Reveal key={c.title} className="cert-card"><div className="flex items-center justify-between"><span className="tile-icon"><Award size={24}/></span><span className={`level ${c.level==='Advanced'?'level-advanced':''}`}>{c.level}</span></div><span className="cert-number font-mono">0{i+1} / {c.year}</span><h3>{c.title}</h3><p>{c.type}</p><Tags items={c.tags}/></Reveal>)}</div></div></section>
      <section id="projects" className="section"><div className="container"><SectionHeading number="05" label="SELECTED WORK" title={p.projectsHeading}/><div className="filter-bar" role="tablist" aria-label="Project category">{p.filters.map(f=><Button key={f} variant="ghost" role="tab" aria-selected={filter===f} className={filter===f?'selected-filter':''} onClick={()=>setFilter(f)}>{f}</Button>)}</div><Reveal className="featured-project"><div className="featured-heading"><div className="eyebrow text-secondary"><Layers3 size={16}/> FEATURED CASE STUDY</div><span className="font-mono text-muted-foreground">01 / OSPIRA</span></div><h3>{p.featured.title}</h3><Tags items={p.featured.tech}/><div className="problem-solution"><div><h4>{p.labels.problem}</h4><p>{p.featured.problem}</p></div><div><h4 className="text-secondary">{p.labels.solution}</h4><p>{p.featured.solution}</p></div></div><div className="project-stats">{p.featured.stats.map(s=><div key={s.label}><strong><Count value={s.value} suffix={s.suffix}/></strong><span>{s.label}</span></div>)}</div><Dialog><DialogTrigger asChild><Button variant="outline">{p.labels.architecture}<ArrowUpRight/></Button></DialogTrigger><DialogContent className="architecture-modal"><DialogHeader><DialogTitle>OSPIRA — {p.labels.architecture}</DialogTitle><DialogDescription>{p.featured.title}</DialogDescription></DialogHeader><div className="architecture-flow">{p.featured.architecture.map((n,i)=><div key={n} className="architecture-step"><div className="architecture-node">{i===0?<Atom/>:i===1?<Terminal/>:<Workflow/>}<span>{n}</span></div><ArrowDown className="text-secondary"/></div>)}<div className="architecture-services">{p.featured.services.map(n=><div key={n} className="architecture-node"><Database size={18}/>{n}</div>)}</div></div></DialogContent></Dialog></Reveal>
      <h3 className="subsection-heading">{p.labels.features}<span className="font-mono">/ {String(p.features.filter(f=>filter==='All'||f.category===filter).length).padStart(2,'0')}</span></h3><div className="features-grid">{p.features.map((f,i)=>{if(filter!=='All'&&f.category!==filter)return null;const Icon=featureIcons[i] ?? Layers3;const open=expanded.includes(i);return <Reveal key={f.title} className={`feature-card ${open?'feature-open':''}`}><Button variant="ghost" className="feature-trigger" aria-expanded={open} aria-controls={`feature-${i}`} onClick={()=>setExpanded(v=>open?v.filter(n=>n!==i):[...v,i])}><Icon size={21}/><span>{f.title}</span><ChevronDown className={open?'rotate-180':''}/></Button><p id={`feature-${i}`} className={open?'feature-text expanded':'feature-text'}>{f.text}</p></Reveal>;})}</div>
      <h3 className="subsection-heading">{p.labels.applications}</h3><div className="applications-grid">{p.applications.map((a,i)=>{if(filter!=='All'&&!a.categories.includes(filter))return null;const Icon=appIcons[i] ?? Globe;return <Reveal key={a.title} className="application-card"><div className="flex justify-between items-center"><span className="tile-icon"><Icon size={22}/></span><span className="coming-soon"><LockKeyhole size={11}/>{p.labels.comingSoon}</span></div><h4>{a.title}</h4><p>{a.text}</p><Tags items={a.tech}/><Button disabled variant="ghost" className="app-button" aria-label={`${a.title} — Coming Soon`}>{p.labels.comingSoon}<ArrowUpRight/></Button></Reveal>;})}</div></div></section>
      <section id="contact" className="section section-tinted"><div className="container contact-grid"><Reveal><div className="eyebrow"><span>06 /</span> CONTACT</div><h2 className="contact-heading">{p.contact.heading}</h2><div className="contact-details"><div><Mail size={19}/>{p.contact.email?<a href={`mailto:${p.contact.email}`}>{p.contact.email}</a>:<span>{p.labels.email}</span>}</div><div><MapPin size={19}/>{p.contact.location}</div></div><div className="flex gap-3 mt-8">{[{url:p.contact.github,label:p.labels.github,Icon:Github},{url:p.contact.linkedin,label:p.labels.linkedin,Icon:Linkedin}].map(({url,label,Icon})=>url?<Button key={label} asChild size="icon" variant="outline"><a href={url} aria-label={label} target="_blank" rel="noreferrer"><Icon/></a></Button>:<Button key={label} disabled size="icon" variant="outline" aria-label={label} title={label}><Icon/></Button>)}</div></Reveal><Reveal><form onSubmit={submit} className="contact-form"><div className="form-row"><label>{p.labels.name}<input name="name" autoComplete="name" required placeholder="Your name"/></label><label>{p.labels.emailField}<input name="email" type="email" autoComplete="email" required placeholder="you@example.com"/></label></div><label>{p.labels.message}<textarea name="message" rows={5} required placeholder="Your message"/></label><Button type="submit" size="lg">{p.labels.send}<Send/></Button>{feedback&&<p role="status" className="form-feedback">{feedback}</p>}</form></Reveal></div></section>
    </main><footer><div className="container footer-inner"><a href="#" className="brand"><span className="brand-mark"><Braces size={19}/></span>{p.name}<span className="text-primary">.</span></a><span>{p.copyright}</span><Button variant="outline" size="icon" asChild><a href="#" aria-label="Back to top" title="Back to top"><ArrowUp/></a></Button></div></footer>
  </div>;
}
